apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  name: artifactory-registry
disableNameSuffixHash: true
type: "kubernetes.io/dockerconfigjson"
files:
  - .dockerconfigjson=artifactory-registry-creds.enc.json
