apiVersion: apps/v1
kind: Deployment
metadata:
  name: knight-light-server-java
spec:
  template:
    spec:
      containers:
        - name: knight-light-server-java
          securityContext:
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
            capabilities:
              add:
                - SYS_PTRACE