apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitestream
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      micro-svc: sitestream 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    spec:
      terminationGracePeriodSeconds: 15
      imagePullSecrets:
        - name: artifactory-registry
      containers:
        - name: sitestream 
          image: sitestream 
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 0.5
              memory: 256Mi
            requests:
              cpu: 0.1
              memory: 64Mi
          workingDir: /app
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: sitestream-secret
