
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: knight-light

  
resources:
- base/

images:
- name: knight-light-server-flask
  newName: some-experimental-image
  newTag: abc123
- name: knight-light-server-go
  newName: some-image
  newTag: latest
- name: knight-light-server-java
  newName: artifactory.cloud.cms.gov/batcave-docker/ado-repositories/nightwing/knight-light/knight-light-server-java
  newTag: a519abb1
- name: knight-light-server-nodejs
  newName: artifactory.cloud.cms.gov/batcave-docker/ado-repositories/nightwing/knight-light/knight-light-server-nodejs
  newTag: cb130c39
- name: knight-light-ui
  newName: artifactory.cloud.cms.gov/batcave-docker/ado-repositories/nightwing/knight-light/knight-light-ui
  newTag: "37790114"

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: knight-light
    spec:
      template:
        spec:
          tolerations:
            - key: "knightlight"
              operator: "Exists"
              effect: "NoSchedule"
  target:
    kind: Deployment
