apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: knight-light

  
resources:
- base/

images:
- name: ghcr.io/cms-enterprise/batcave/knight-light-go-server
  newTag: 3d08bc98
- name: ghcr.io/cms-enterprise/batcave/knight-light-ui
  newTag: b8ae2e44
- name: knight-light-server-flask
  newName: artifactory.cloud.cms.gov/batcave-docker/ado-repositories/nightwing/knight-light/knight-light-server-flask
  newTag: 208c3e6f
- name: knight-light-server-go
  newName: artifactory.cloud.cms.gov/batcave-docker/ado-repositories/nightwing/knight-light/knight-light-server
  newTag: b09a78f9
- name: knight-light-server-java
  newName: artifactory.cloud.cms.gov/batcave-docker/ado-repositories/nightwing/knight-light/knight-light-server-java
  newTag: 681e80e5-rfstub
- name: knight-light-server-nodejs
  newName: artifactory.cloud.cms.gov/batcave-docker/ado-repositories/nightwing/knight-light/knight-light-server-nodejs
  newTag: 93a6caaa
- name: knight-light-ui
  newName: artifactory.cloud.cms.gov/batcave-docker/ado-repositories/nightwing/knight-light/knight-light-ui
  newTag: e4363fe3

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: knight-light
    spec:
      template:
        spec:
          tolerations:
            - key: "knightlight"
              operator: "Exists"
              effect: "NoSchedule"
  target:
    kind: Deployment

patchesStrategicMerge:
- container-patches/patch-knight-light-server-flask.yaml
- container-patches/patch-knight-light-server-go.yaml
- container-patches/patch-knight-light-server-java.yaml
- container-patches/patch-knight-light-server-nodejs.yaml
- container-patches/patch-knight-light-ui.yaml
