apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitestream 
spec:
  template:
    spec:
      containers:
        - name: sitestream 
          securityContext:
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
            capabilities:
              add:
                - SYS_PTRACE
