apiVersion: apps/v1
kind: Deployment
metadata:
  name: knight-light-server-flask
spec:
  template:
    spec:
      containers:
        - name: knight-light-server-flask
          securityContext:
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
            capabilities:
              add:
                - SYS_PTRACE