apiVersion: apps/v1
kind: Deployment
metadata:
  name: knight-light-mono-counter-api
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      micro-svc: knight-light-mono-counter-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    spec:
      terminationGracePeriodSeconds: 15
      imagePullSecrets:
        - name: artifactory-registry
      containers:
        - name: knight-light-mono-counter-api
          image: knight-light-mono-counter-api
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 0.5
              memory: 512Mi
            requests:
              cpu: 0.1
              memory: 64Mi
          workingDir: /app
          ports:
            - containerPort: 8080
            
